spring:
  application:
    name: web-login

  # MySQL 配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver # MySQL驱动，无需修改
    url: jdbc:mysql://localhost:3306/login?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    username: root # 数据库连接名
    password: root # 数据库连接密码

  # Redis 配置
  redis:
    host: 127.0.0.1 # Redis地址，本地为127.0.0.1
    port: 6379 # Redis端口号，默认为6379
    password: # Redis密码，没有请保持为空
    timeout: 60000
    lettuce:
      pool:
        max-active: 10 # 最大连接数
        max-idle: 5 # 最大空闲连接 默认8
        min-idle: 2 # 最小空闲连接
        max-wait: -1 # 最大连接阻塞等待时间 默认-1

  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: true
    prefix: classpath:/templates/

  # MyBatis配置
  mybatis:
    mapper-locations: classpath:/mapper/**/*.xml
    type-aliases-package: cn.hzu.weblogin.dao
    type-enums-package: cn.hzu.weblogin.model.enums

  # 服务启动
  server:
    port: 8080
    # 公网暴露 IP
    addr: http://127.0.0.1:${server.port}

  # 项目配置
  project:
    # 腾讯云短信验证码配置
    # sms:
    #app-id: # 应用 SDK AppID
    #app-key: # 应用 App Key
    #template-id: # 短信正文ID
    #sign: # 短信签名
    # 短信发送分钟间隔
    #interval-min: 1
    # 短信有效分钟
    #valid-min: 5

